### ISSUE TITLE
algorithm for Util.lineSegmentIntersection

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/dot#30] opened 2015-06-15 18:24 UTC
In Util.js:

``` js
    /*
     * Computes the intersection of two line segments. Algorithm taked from Paul Bourke, 1989:
     * http://astronomy.swin.edu.au/~pbourke/geometry/lineline2d/
     * Ported from MathUtil.java on 9/20/2013 by @samreid
     * line a goes from point 1->2 and line b goes from 3->4
     * @returns a Vector2 of the intersection point, or null if no intersection
     */
    lineSegmentIntersection: function( x1, y1, x2, y2, x3, y3, x4, y4 ) {
```

The URL is broken, so difficult to determin what "takes from" (sic) means.  Assigning to @jonathanolson to evaluate whether there's a third-party licensing issue here.

**Comment by jonathanolson** [comment] 2015-06-15 19:15
@samreid, do you recall the "upgrade piccolo incident"? MathUtil.java was 'created' in that commit, noting "un-deleted all files that were lost in the 'upgrade piccolo incident'".

I can't find history or commit messages for when it was truly added before, but that code's at least 10 years old.

**Comment by samreid** [comment] 2015-06-15 21:07
Here's a Bourke reference:
http://paulbourke.net/geometry/pointlineplane/pdb.c
parent page is:
http://paulbourke.net/geometry/pointlineplane/

**Comment by samreid** [comment] 2015-06-15 21:23
The "undeleted all files" commit is from Nov 2005, svn revision 5790.  Hunting around online, I found the path for svn revision 5000 to be right here:
https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fphetcommon%2Fsrc%2Fedu%2Fcolorado%2Fphet%2Fcommon%2Fmath%2FMathUtil.java&commit=5000

that is, svn/5000/trunk/phetcommon/src/edu/colorado/phet/common/math/MathUtil.java

r5000 contains bourke algorithms.

**Comment by samreid** [comment] 2015-06-15 21:24
@jonathanolson and @pixelzoom is this enough to go on? Should we add it to an upcoming meeting agenda?

**Comment by pixelzoom** [comment] 2015-06-15 21:29
I'm not familiar with the algorithm or whether there's a licensing issue here, I only stumbled upon it.  So I'm the wrong person to ask.

**Comment by samreid** [comment] 2015-06-15 22:26
I see several algorithms in this file that look like we did not write them ourselves.  Would be good to identify them.  I'll create a separate issue for that (this can be a sub-issue).

**Comment by samreid** [comment] 2015-06-15 22:31
I noted this and other potential issues in #31

**Comment by andrea-phet** [comment] 2016-06-29 16:55
A problem occurred in one of the sims that was caused by the lineSegmentIntersection algorithm, noted in #53, so I used a small epsilon value instead of zero to check if the intersection exists. This fixes the problem, however, use of the epsilon value may not be a robust way to check for segment segment intersection. I will try to look for a new implementation of lineSegmentIntersection. Also, the error may be introduced by the linelineIntersection algorithm which lineSegmentIntersection uses.

**Comment by andrea-phet** [comment] 2017-08-15 16:21
lineSegmentIntersection done. Assigning to @jonathanolson to review.

**Comment by jonathanolson** [comment] 2017-09-27 04:43
Ran into issues tonight with this function, will take the time to review here.

Tried running:
```js
dot.Util.lineSegmentIntersection( 30.353261553154365, 16.69400908470202, 72.78826487008264, 73.88814243860902, 72.78826487008264, 73.88814243860902, 89.96204100680747, 97.03505337951492 );
```
of two lines, essentially:

- 30.353261553154365, 16.69400908470202 => 72.78826487008264, 73.88814243860902
- 72.78826487008264, 73.88814243860902 => 89.96204100680747, 97.03505337951492

The current code returns ```Vector2 {x: 85.33333333333333, y: 85.33333333333333}```, while the old code returns the shared endpoint (```Vector2 {x: 72.78826487008264, y: 73.88814243860902}```).

Investigating and reviewing.

**Comment by jonathanolson** [comment] 2017-09-27 04:50
Adding an epsilon for the denominator properly detects this case.

**Comment by jonathanolson** [comment] 2017-11-02 21:25
Failing for:
```js
dot.Util.lineSegmentIntersection( 293.1293439302738, 314.4245163440668, 288.8867032431545, 321.21274144345773, 288.8867032431545, 321.21274144345773, 288.8867031926097, 321.2127414940025 )
```
where the true intersection point would be at the shared endpoint (not a point that is 0.0007806235324924636 in distance from the shared endpoint).

**Comment by veillette** [comment] 2023-04-03 19:22
Yes adding the epsilon check and also handling the case where it is an exact endpoint overlap does the trick. Closing

**Closed by veillette** 2023-04-03 19:22 UTC
Labels: priority:4-low, status:ready-for-review
